const IMG="assets/images/";
const defaultGame={version:2,cycle:1,lastTick:Date.now(),selectedPlanet:0,activeMenu:"command",resources:{metal:260,crystal:130,fuel:120,energy:90,credits:450},storage:{metal:1500,crystal:1000,fuel:900,energy:999,credits:999999},buildings:{mine:1,crystalExtractor:1,refinery:1,solarPlant:1,shipyard:1,researchLab:1,market:1,defenseGrid:0,habitat:1},fleet:{fighters:2,frigates:0,destroyers:0,scouts:1,transports:0},research:{warp:0,plasma:0,ai:0,terraforming:0,economy:0},defense:{turrets:0,shields:0,mines:0},inventory:{alloy:35,cells:12,repair:2},xp:0,level:1,messages:[],missionsDone:0};
const buildingData={mine:{name:"Mine de métal",icon:"⛏️",desc:"Produit du métal à chaque cycle.",cost:{credits:90,energy:8},gain:{metal:8}},crystalExtractor:{name:"Extracteur de cristal",icon:"💎",desc:"Produit du cristal rare.",cost:{metal:90,credits:80,energy:10},gain:{crystal:5}},refinery:{name:"Raffinerie carburant",icon:"⛽",desc:"Convertit l'énergie locale en carburant.",cost:{metal:120,crystal:35},gain:{fuel:4}},solarPlant:{name:"Centrale solaire",icon:"⚡",desc:"Augmente l'énergie disponible et les bonus de prod.",cost:{metal:100,credits:70},gain:{energy:7}},shipyard:{name:"Chantier orbital",icon:"🛠️",desc:"Débloque et accélère la construction de vaisseaux.",cost:{metal:180,crystal:80,credits:150}},researchLab:{name:"Laboratoire",icon:"🔬",desc:"Débloque les technologies avancées.",cost:{crystal:100,credits:180}},market:{name:"Marché galactique",icon:"🏦",desc:"Améliore les échanges et les crédits par cycle.",cost:{crystal:80,metal:100},gain:{credits:10}},defenseGrid:{name:"Grille défensive",icon:"🛡️",desc:"Débloque tourelles, boucliers et mines orbitales.",cost:{metal:220,crystal:90,credits:160}},habitat:{name:"Habitat civil",icon:"👥",desc:"Augmente la population et les revenus.",cost:{metal:120,credits:130},gain:{credits:6}}};
const shipData={scouts:{name:"Sonde éclaireuse",icon:"🛰️",cost:{metal:45,crystal:20,fuel:10,credits:35},power:1,need:{shipyard:1}},fighters:{name:"Chasseur",icon:"🚀",cost:{metal:70,crystal:12,fuel:8,credits:55},power:5,need:{shipyard:1}},frigates:{name:"Frégate",icon:"🛸",cost:{metal:180,crystal:80,fuel:35,credits:150},power:22,need:{shipyard:2}},destroyers:{name:"Destroyer",icon:"💥",cost:{metal:480,crystal:210,fuel:90,credits:430},power:75,need:{shipyard:4}},transports:{name:"Transporteur",icon:"🚚",cost:{metal:220,crystal:50,fuel:60,credits:180},power:8,need:{shipyard:2}}};
const techData={warp:{name:"Moteur Warp",icon:"🚀",desc:"Réduit le coût carburant des missions.",cost:{crystal:120,credits:180},max:5},plasma:{name:"Armes Plasma",icon:"🔥",desc:"Augmente la puissance militaire.",cost:{metal:180,crystal:120,credits:220},max:5},ai:{name:"IA tactique",icon:"🧠",desc:"Améliore les chances de réussite.",cost:{crystal:160,credits:260},max:5},terraforming:{name:"Terraforming",icon:"🌍",desc:"Augmente la production globale.",cost:{crystal:240,energy:40,credits:380},max:3},economy:{name:"Réseau commercial",icon:"📈",desc:"Augmente les crédits par cycle.",cost:{crystal:100,credits:150},max:5}};
const planets=[{name:"Nova Prime",img:IMG+"NovaPrime.png",orbit:170,size:74,angle:20,type:"Monde océanique",desc:"Capitale maritime stable.",bonus:"Crédits +5%"},{name:"Meridian",img:IMG+"Meridian.png",orbit:240,size:78,angle:95,type:"Désert minier",desc:"Déserts rouges et minerais rares.",bonus:"Métal +10%"},{name:"Terra Nova",img:IMG+"TerraNova.png",orbit:300,size:82,angle:10,type:"Monde habitable",desc:"Atmosphère stable et colonies civiles.",bonus:"Habitat +10%"},{name:"Volcanis",img:IMG+"Volcanis.png",orbit:360,size:88,angle:45,type:"Volcanique",desc:"Tectonique extrême et forges orbitales.",bonus:"Chantiers -5%"},{name:"Luxora",img:IMG+"Luxora.png",orbit:420,size:72,angle:75,type:"Lune rocheuse",desc:"Ressources souterraines profondes.",bonus:"Stockage +10%"},{name:"Aurora",img:IMG+"Aurora.png",orbit:480,size:92,angle:105,type:"Cristalline",desc:"Énergie inconnue détectée.",bonus:"Cristal +10%"},{name:"Thalos",img:IMG+"Thalos.png",orbit:540,size:82,angle:145,type:"Monde nocturne",desc:"Vents glacials et signaux pirates.",bonus:"Missions +5%"},{name:"Voranis",img:IMG+"Voranis.png",orbit:610,size:125,angle:190,type:"Géante gazeuse",desc:"Tempêtes massives visibles depuis l'orbite.",bonus:"Fuel +10%"},{name:"Crystalia",img:IMG+"Crystalia.png",orbit:690,size:92,angle:225,type:"Monde gelé",desc:"Ruines anciennes sous la glace.",bonus:"Recherche +5%"},{name:"Elysia",img:IMG+"Elysia.png",orbit:760,size:76,angle:270,type:"Monde mort",desc:"Silence radio total depuis plusieurs cycles.",bonus:"Défense +5%"}];
let game=loadGame();
let panel=document.getElementById("mainPanel");
let tickTimer=null;
function clone(o){return JSON.parse(JSON.stringify(o))}
function loadGame(){const raw=localStorage.getItem("echoGalacticaSave");if(!raw)return clone(defaultGame);try{return merge(clone(defaultGame),JSON.parse(raw))}catch(e){return clone(defaultGame)}}
function merge(a,b){for(const k in b){if(b[k]&&typeof b[k]==="object"&&!Array.isArray(b[k]))a[k]=merge(a[k]||{},b[k]);else a[k]=b[k]}return a}
function saveGame(){game.lastTick=Date.now();localStorage.setItem("echoGalacticaSave",JSON.stringify(game));toast("Sauvegarde effectuée")}
function resetGame(){if(!confirm("Supprimer la sauvegarde Echo Galactica ?"))return;localStorage.removeItem("echoGalacticaSave");location.reload()}
function fmt(n){return Math.floor(n).toLocaleString("fr-FR")}
function costFor(base,lvl){const out={};for(const r in base)out[r]=Math.ceil(base[r]*(1+lvl*.72)*Math.pow(1.18,lvl-1));return out}
function hasCost(cost){return Object.keys(cost).every(r=>(game.resources[r]||0)>=cost[r])}
function pay(cost){if(!hasCost(cost))return false;for(const r in cost)game.resources[r]-=cost[r];return true}
function costHtml(cost){return Object.entries(cost).map(([r,v])=>`${labelRes(r)} ${fmt(v)}`).join(" · ")}
function labelRes(r){return{metal:"Métal",crystal:"Cristal",fuel:"Fuel",energy:"Énergie",credits:"Crédits"}[r]||r}
function production(){const b=game.buildings,t=game.research,p=planets[game.selectedPlanet];let mult=1+t.terraforming*.06;if(p.name==="Meridian")mult+=.1;let prod={metal:b.mine*8*mult,crystal:b.crystalExtractor*5*mult,fuel:b.refinery*4*mult,energy:b.solarPlant*7,credits:(b.market*10+b.habitat*6)*(1+t.economy*.08)};if(p.name==="Aurora")prod.crystal*=1.1;if(p.name==="Voranis")prod.fuel*=1.1;if(p.name==="Nova Prime")prod.credits*=1.05;return prod}
function tick(mult=1){const prod=production();for(const r in prod){game.resources[r]=Math.min(game.storage[r]||999999,game.resources[r]+prod[r]*mult)}game.cycle+=mult;game.xp+=.3*mult;if(game.xp>=game.level*100){game.xp=0;game.level++;addLog("Promotion obtenue : niveau "+game.level)}updateStaticPanels();if(game.activeMenu)render(game.activeMenu,false)}
function getPower(){let base=0;for(const s in game.fleet)base+=(shipData[s]?.power||0)*game.fleet[s];return Math.floor(base*(1+game.research.plasma*.08+game.research.ai*.04))}
function addLog(txt){game.messages.unshift({t:Date.now(),txt});game.messages=game.messages.slice(0,30);updateStaticPanels()}
function toast(txt){const old=document.querySelector(".toast");if(old)old.remove();const el=document.createElement("div");el.className="toast";el.textContent=txt;document.body.appendChild(el);setTimeout(()=>el.classList.add("hide"),1200);setTimeout(()=>el.remove(),1600)}
function spendMissing(cost){return Object.entries(cost).filter(([r,v])=>(game.resources[r]||0)<v).map(([r])=>labelRes(r)).join(", ")}
function upgradeBuilding(id){const lvl=game.buildings[id]||0,cost=costFor(buildingData[id].cost,lvl+1);if(!pay(cost)){toast("Manque : "+spendMissing(cost));return}game.buildings[id]=lvl+1;game.xp+=8+lvl*2;addLog(`${buildingData[id].name} amélioré niv. ${game.buildings[id]}`);render("construction")}
function buyShip(id){const data=shipData[id],need=data.need||{};for(const b in need)if((game.buildings[b]||0)<need[b]){toast(`Requis : ${buildingData[b].name} niv. ${need[b]}`);return}let cost=clone(data.cost);if(planets[game.selectedPlanet].name==="Volcanis")for(const r in cost)cost[r]=Math.ceil(cost[r]*.95);if(!pay(cost)){toast("Ressources insuffisantes");return}game.fleet[id]++;game.xp+=5;addLog(`${data.name} construit`);render(game.activeMenu)}
function upgradeTech(id){const data=techData[id],lvl=game.research[id]||0;if(lvl>=data.max){toast("Technologie au niveau max");return}if(game.buildings.researchLab<1){toast("Laboratoire requis");return}const cost=costFor(data.cost,lvl+1);if(!pay(cost)){toast("Manque : "+spendMissing(cost));return}game.research[id]++;game.xp+=15;addLog(`${data.name} recherché niv. ${game.research[id]}`);render(game.activeMenu)}
function buyDefense(id){const map={turrets:{name:"Tourelle laser",cost:{metal:90,crystal:20,credits:70}},shields:{name:"Bouclier",cost:{metal:160,crystal:80,energy:20,credits:140}},mines:{name:"Mines orbitales",cost:{metal:120,fuel:40,credits:90}}};if(game.buildings.defenseGrid<1){toast("Construis d'abord la grille défensive");return}if(!pay(map[id].cost)){toast("Ressources insuffisantes");return}game.defense[id]++;addLog(`${map[id].name} installé`);render("defense")}
function runMission(id){const missions={scan:{name:"Scanner les astéroïdes",fuel:18,power:0,reward:()=>({crystal:Math.floor(45+Math.random()*75),metal:Math.floor(30+Math.random()*60)})},pirates:{name:"Chasser les pirates",fuel:28,power:20,reward:()=>({credits:Math.floor(140+Math.random()*220),alloy:8})},ruins:{name:"Ruines de Crystalia",fuel:42,power:45,reward:()=>({crystal:Math.floor(130+Math.random()*180),credits:Math.floor(90+Math.random()*160),repair:1})}}[id];const fuelCost=Math.max(5,Math.ceil(missions.fuel*(1-game.research.warp*.07)));if(game.resources.fuel<fuelCost){toast("Pas assez de fuel");return}if(getPower()<missions.power){toast("Puissance flotte insuffisante");return}game.resources.fuel-=fuelCost;const chance=Math.min(.92,.58+getPower()/220+game.research.ai*.045);if(Math.random()<chance){const reward=missions.reward();let parts=[];for(const r in reward){if(game.resources[r]!==undefined)game.resources[r]=Math.min(game.storage[r]||999999,game.resources[r]+reward[r]);else game.inventory[r]=(game.inventory[r]||0)+reward[r];parts.push(`${labelRes(r)} +${fmt(reward[r])}`)}game.missionsDone++;game.xp+=18;addLog(`${missions.name} réussie : ${parts.join(" · ")}`)}else{if(game.fleet.fighters>0){game.fleet.fighters--;addLog(`${missions.name} échouée : 1 chasseur perdu`)}else addLog(`${missions.name} échouée`)}render("missions")}
function trade(type){const rates={buyCrystal:{pay:{credits:120},gain:{crystal:60}},buyFuel:{pay:{credits:95},gain:{fuel:70}},sellMetal:{pay:{metal:120},gain:{credits:85}},sellCrystal:{pay:{crystal:50},gain:{credits:130}}}[type];if(!pay(rates.pay)){toast("Transaction impossible");return}for(const r in rates.gain)game.resources[r]=Math.min(game.storage[r]||999999,game.resources[r]+rates.gain[r]);addLog("Transaction marché effectuée");render("market")}
function resourceBar(){const prod=production();return `<div class="resource-bar">${Object.entries(game.resources).map(([r,v])=>`<div class="resource"><span>${labelRes(r)}</span><b>${fmt(v)}</b><em>+${fmt(prod[r]||0)}/cycle</em></div>`).join("")}</div>`}
function render(key,save=true){game.activeMenu=key;if(save)localStorage.setItem("echoGalacticaSave",JSON.stringify(game));document.querySelectorAll("[data-menu]").forEach(b=>b.classList.toggle("active",b.dataset.menu===key));panel.innerHTML=resourceBar()+(views[key]?views[key]():views.command());wirePanel(key);updateStaticPanels()}
const views={command:()=>`<h1>Command Center</h1><p>Bienvenue commandant. Colonie active sur <b>${planets[game.selectedPlanet].name}</b>. Le jeu tourne en temps réel : production, upgrades, flotte, recherche et missions.</p><div class="grid four" style="margin-top:10px"><div class="card"><strong>⚔️ Puissance</strong><small>${fmt(getPower())} pts</small></div><div class="card"><strong>🏛️ Niveau empire</strong><small>${game.level} · XP ${fmt(game.xp)}/${game.level*100}</small></div><div class="card"><strong>🔁 Cycle</strong><small>${fmt(game.cycle)}</small></div><div class="card"><strong>📋 Missions</strong><small>${fmt(game.missionsDone)} réussies</small></div></div><div class="section-title">Actions rapides</div><div class="grid"><button class="btn" data-action="tick">Passer 1 cycle</button><button class="btn" data-action="save">Sauvegarder</button><button class="btn danger" data-action="reset">Reset</button></div><div class="section-title">Journal</div><div class="list">${game.messages.slice(0,8).map(m=>`<div class="row">➜ <span>${m.txt}</span></div>`).join("")||`<div class="row">➜ Nouvelle colonie créée.</div>`}</div>`,
systems:()=>{const size=500,cx=size/2;let html=`<h1>Systems</h1><div class="sys-wrap"><div class="sys-map" style="width:${size}px;height:${size}px"><div class="sun"></div>`;planets.forEach((p,i)=>{const r=p.orbit*(size/1620),s=Math.max(18,Math.round(p.size*(size/1620))),x=cx+Math.cos(p.angle*Math.PI/180)*r-s/2,y=cx+Math.sin(p.angle*Math.PI/180)*r-s/2;html+=`<div class="orbit-ring" style="width:${r*2}px;height:${r*2}px;left:${cx-r}px;top:${cx-r}px"></div><div class="planet-dot ${i===game.selectedPlanet?"selected":""}" data-planet="${i}" style="width:${s}px;height:${s}px;left:${x}px;top:${y}px"><img src="${p.img}" onerror="this.style.display='none'"></div>`});const p=planets[game.selectedPlanet];html+=`</div><div class="planet-info"><h2>${p.name}</h2><p>Type : ${p.type}</p><p>${p.desc}</p><p class="good">Bonus actif : ${p.bonus}</p><button class="btn" data-menujump="construction">Gérer cette colonie</button></div></div><div class="planet-bar">${planets.map((p,i)=>`<button class="planet-mini ${i===game.selectedPlanet?"active":""}" data-planet="${i}"><img src="${p.img}" onerror="this.style.display='none'"><span>${p.name}</span></button>`).join("")}</div>`;return html},
construction:()=>`<h1>Construction</h1><p>Chaque bâtiment augmente vraiment ta production ou débloque des systèmes.</p><div class="grid two">${Object.entries(buildingData).map(([id,b])=>{const lvl=game.buildings[id]||0,cost=costFor(b.cost,lvl+1);return `<div class="card"><strong>${b.icon} ${b.name} <span class="tag">Niv. ${lvl}</span></strong><small>${b.desc}</small><small>Coût : ${costHtml(cost)}</small><button class="btn" data-upbuild="${id}" ${hasCost(cost)?"":"disabled"}>Améliorer</button></div>`}).join("")}</div>`,
shipyard:()=>`<h1>Shipyard</h1><p>Construis des vaisseaux. Certains demandent un chantier orbital plus avancé.</p><div class="grid two">${Object.entries(shipData).map(([id,s])=>`<div class="card"><strong>${s.icon} ${s.name} <span class="tag green">x${game.fleet[id]}</span></strong><small>Puissance : ${s.power} · Requis chantier niv. ${s.need.shipyard}</small><small>Coût : ${costHtml(s.cost)}</small><button class="btn" data-buyship="${id}">Construire</button></div>`).join("")}</div>`,
fleet:()=>`<h1>Fleet</h1><div class="grid four"><div class="card"><strong>⚔️ Puissance totale</strong><small>${fmt(getPower())}</small></div><div class="card"><strong>🚀 Vaisseaux</strong><small>${fmt(Object.values(game.fleet).reduce((a,b)=>a+b,0))}</small></div><div class="card"><strong>🧠 Bonus IA</strong><small>+${game.research.ai*4}% tactique</small></div><div class="card"><strong>🔥 Plasma</strong><small>+${game.research.plasma*8}% dégâts</small></div></div><div class="section-title">Composition</div><div class="list">${Object.entries(shipData).map(([id,s])=>`<div class="row"><span>${s.icon}</span><div class="grow"><b>${s.name}</b><br><span class="muted">${game.fleet[id]} unité(s) · ${s.power} puissance/u</span></div><button class="btn" data-buyship="${id}">+</button></div>`).join("")}</div>`,
research:()=>`<h1>Research</h1><p>Les technos modifient les calculs du jeu : production, combat, missions et déplacement.</p><div class="list">${Object.entries(techData).map(([id,t])=>{const lvl=game.research[id],cost=costFor(t.cost,lvl+1),pct=Math.floor(lvl/t.max*100);return `<div class="row"><div class="grow"><b>${t.icon} ${t.name}</b><br><span class="muted">${t.desc}</span><div class="progress"><i style="width:${pct}%"></i></div><small>Niv. ${lvl}/${t.max} ${lvl<t.max?" · Coût : "+costHtml(cost):" · MAX"}</small></div><button class="btn" data-tech="${id}" ${lvl>=t.max?"disabled":""}>Rechercher</button></div>`}).join("")}</div>`,
missions:()=>`<h1>Missions</h1><p>Envoie ta flotte. Les chances dépendent de ta puissance et de l'IA tactique.</p><div class="grid"><div class="card"><strong>🛰️ Scanner les astéroïdes</strong><small>Fuel 18 · danger faible · récompense métal/cristal</small><button class="btn" data-mission="scan">Lancer</button></div><div class="card"><strong>☠️ Chasser les pirates</strong><small>Fuel 28 · puissance 20 · récompense crédits</small><button class="btn" data-mission="pirates">Lancer</button></div><div class="card"><strong>❄️ Ruines de Crystalia</strong><small>Fuel 42 · puissance 45 · récompense rare</small><button class="btn" data-mission="ruins">Lancer</button></div></div>`,
market:()=>`<h1>Market</h1><p>Achats/ventes instantanés. Le niveau du marché augmente les revenus passifs.</p><div class="grid two"><button class="btn" data-trade="buyCrystal">Acheter 60 cristal · 120 crédits</button><button class="btn" data-trade="buyFuel">Acheter 70 fuel · 95 crédits</button><button class="btn" data-trade="sellMetal">Vendre 120 métal · 85 crédits</button><button class="btn" data-trade="sellCrystal">Vendre 50 cristal · 130 crédits</button></div>`,
defense:()=>`<h1>Defense</h1><p>Installe une grille défensive puis renforce tes planètes.</p><div class="grid"><div class="card"><strong>🔫 Tourelles laser <span class="tag">x${game.defense.turrets}</span></strong><small>Métal 90 · Cristal 20 · Crédits 70</small><button class="btn" data-defense="turrets">Installer</button></div><div class="card"><strong>🛡️ Boucliers <span class="tag">x${game.defense.shields}</span></strong><small>Métal 160 · Cristal 80 · Énergie 20 · Crédits 140</small><button class="btn" data-defense="shields">Installer</button></div><div class="card"><strong>💣 Mines orbitales <span class="tag">x${game.defense.mines}</span></strong><small>Métal 120 · Fuel 40 · Crédits 90</small><button class="btn" data-defense="mines">Installer</button></div></div>`,
technology:()=>views.research(),galaxy:()=>`<h1>Galaxy Map</h1><p>Carte vivante du secteur. Sélectionne une planète dans Systems pour changer le bonus de colonie.</p><div class="card" style="height:390px"><canvas id="bigGalaxy"></canvas></div>`,profile:()=>`<h1>Profile</h1><div class="grid two"><div class="card"><strong>Commandant Echo</strong><small>Rang : Amiral de la Nébuleuse</small><small>Niveau ${game.level} · XP ${fmt(game.xp)}</small></div><div class="card"><strong>Statistiques</strong><small>Cycles : ${fmt(game.cycle)}</small><small>Missions réussies : ${fmt(game.missionsDone)}</small></div></div>`,settings:()=>`<h1>Settings</h1><div class="grid"><button class="btn" data-action="save">Sauvegarder</button><button class="btn" data-action="tick10">Simuler 10 cycles</button><button class="btn danger" data-action="reset">Reset sauvegarde</button></div>`,alliance:()=>`<h1>Alliance</h1><p>Module alliance prêt pour l'évolution multi-factions.</p><div class="list"><div class="row">👤 EchoX <span class="tag green">CHEF</span></div><div class="row">👤 Vorak <span class="tag">MEMBRE</span></div><div class="row">👤 Lyrra <span class="tag">MEMBRE</span></div></div>`};
function wirePanel(key){panel.querySelectorAll("[data-upbuild]").forEach(b=>b.onclick=()=>upgradeBuilding(b.dataset.upbuild));panel.querySelectorAll("[data-buyship]").forEach(b=>b.onclick=()=>buyShip(b.dataset.buyship));panel.querySelectorAll("[data-tech]").forEach(b=>b.onclick=()=>upgradeTech(b.dataset.tech));panel.querySelectorAll("[data-mission]").forEach(b=>b.onclick=()=>runMission(b.dataset.mission));panel.querySelectorAll("[data-trade]").forEach(b=>b.onclick=()=>trade(b.dataset.trade));panel.querySelectorAll("[data-defense]").forEach(b=>b.onclick=()=>buyDefense(b.dataset.defense));panel.querySelectorAll("[data-planet]").forEach(b=>b.onclick=()=>{game.selectedPlanet=+b.dataset.planet;addLog("Colonie active : "+planets[game.selectedPlanet].name);render("systems")});panel.querySelectorAll("[data-menujump]").forEach(b=>b.onclick=()=>render(b.dataset.menujump));panel.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>{if(b.dataset.action==="save")saveGame();if(b.dataset.action==="reset")resetGame();if(b.dataset.action==="tick")tick(1);if(b.dataset.action==="tick10")tick(10)});if(key==="galaxy")drawBigGalaxy()}
function updateStaticPanels(){document.getElementById("panelInfo").innerHTML=`<div class="info-line"><span>Planète</span><b>${planets[game.selectedPlanet].name}</b></div><div class="info-line"><span>Puissance</span><b>${fmt(getPower())}</b></div><div class="info-line"><span>Cycle</span><b>${fmt(game.cycle)}</b></div><div class="info-line"><span>Prod métal</span><b>+${fmt(production().metal)}</b></div><div class="info-line"><span>Prod crédits</span><b>+${fmt(production().credits)}</b></div>`;drawMini();drawGalaxyPanel()}
function drawMini(){const el=document.getElementById("minimap");if(!el.querySelector("canvas"))el.innerHTML='<canvas id="minimapCanvas"></canvas>';const c=document.getElementById("minimapCanvas"),ctx=c.getContext("2d"),w=c.width=el.clientWidth,h=c.height=el.clientHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle="rgba(0,200,255,.08)";ctx.fillRect(0,0,w,h);ctx.strokeStyle="rgba(0,200,255,.25)";for(let i=0;i<8;i++){ctx.beginPath();ctx.arc(w/2,h/2,12+i*10,0,Math.PI*2);ctx.stroke()}planets.forEach((p,i)=>{const a=p.angle*Math.PI/180,r=15+i*7,x=w/2+Math.cos(a)*r,y=h/2+Math.sin(a)*r;ctx.fillStyle=i===game.selectedPlanet?"#fff":"#00c8ff";ctx.beginPath();ctx.arc(x,y,i===game.selectedPlanet?3.8:2.4,0,Math.PI*2);ctx.fill()})}
function drawGalaxyPanel(){const el=document.getElementById("panelGalaxy");if(!el.querySelector("canvas"))el.innerHTML='<canvas id="galaxyCanvas"></canvas>';const c=document.getElementById("galaxyCanvas"),ctx=c.getContext("2d"),w=c.width=el.clientWidth,h=c.height=el.clientHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle="rgba(0,8,18,.45)";ctx.fillRect(0,0,w,h);for(let i=0;i<55;i++){ctx.fillStyle=`rgba(124,236,255,${.15+Math.random()*.45})`;ctx.fillRect(Math.random()*w,Math.random()*h,1.2,1.2)}ctx.fillStyle="#ffb300";ctx.beginPath();ctx.arc(w*.5,h*.5,5,0,Math.PI*2);ctx.fill();ctx.strokeStyle="rgba(0,200,255,.28)";ctx.strokeRect(4,4,w-8,h-8)}
function drawBigGalaxy(){const c=document.getElementById("bigGalaxy");if(!c)return;const box=c.parentElement,w=c.width=box.clientWidth,h=c.height=box.clientHeight,ctx=c.getContext("2d");ctx.clearRect(0,0,w,h);ctx.fillStyle="rgba(0,8,18,.8)";ctx.fillRect(0,0,w,h);for(let i=0;i<180;i++){ctx.fillStyle=`rgba(124,236,255,${.15+Math.random()*.55})`;ctx.fillRect(Math.random()*w,Math.random()*h,1.4,1.4)}ctx.fillStyle="#ffb300";ctx.beginPath();ctx.arc(w/2,h/2,12,0,Math.PI*2);ctx.fill();planets.forEach((p,i)=>{const r=35+i*18,a=p.angle*Math.PI/180,x=w/2+Math.cos(a)*r,y=h/2+Math.sin(a)*r;ctx.strokeStyle="rgba(0,200,255,.12)";ctx.beginPath();ctx.arc(w/2,h/2,r,0,Math.PI*2);ctx.stroke();ctx.fillStyle=i===game.selectedPlanet?"#fff":"#00c8ff";ctx.beginPath();ctx.arc(x,y,i===game.selectedPlanet?6:4,0,Math.PI*2);ctx.fill();ctx.fillStyle="rgba(220,250,255,.7)";ctx.font="12px Rajdhani";ctx.fillText(p.name,x+8,y+4)})}
function initComms(){const el=document.getElementById("panelComms");el.innerHTML=`<div id="chatLog"></div><div id="chatInputRow"><input id="chatInput" placeholder="Message..." autocomplete="off"><button id="chatSend">▶</button></div>`;const bots=[{u:"Vorak",c:"#ff6b6b",m:["Secteur dégagé.","Ravitaillement terminé.","Ennemi repéré près de Volcanis."]},{u:"Lyrra",c:"#a78bfa",m:["Scan orbital terminé.","Signal faible sur Elysia.","Données reçues commandant."]},{u:"Sys-AI",c:"#fbbf24",m:["[SYS] Production synchronisée.","[SYS] Mission disponible.","[SYS] Sauvegarde auto prête."]}];function msg(u,c,t,mine=false){const div=document.createElement("div");div.className="chat-msg"+(mine?" mine":"");div.innerHTML=`<span class="who" style="color:${c}">${u}</span> <span class="txt">${t}</span>`;document.getElementById("chatLog").appendChild(div);document.getElementById("chatLog").scrollTop=99999}msg("Sys-AI","#fbbf24","[SYS] Interface évolutive chargée.");document.getElementById("chatSend").onclick=()=>{const input=document.getElementById("chatInput"),t=input.value.trim();if(!t)return;msg("Echo","#7cecff",t,true);input.value="";setTimeout(()=>{const b=bots[Math.floor(Math.random()*bots.length)];msg(b.u,b.c,b.m[Math.floor(Math.random()*b.m.length)])},700)};document.getElementById("chatInput").onkeydown=e=>{if(e.key==="Enter")document.getElementById("chatSend").click()};setInterval(()=>{const b=bots[Math.floor(Math.random()*bots.length)];msg(b.u,b.c,b.m[Math.floor(Math.random()*b.m.length)])},14000)}
document.querySelectorAll("[data-menu]").forEach(btn=>btn.onclick=()=>render(btn.dataset.menu));window.addEventListener("resize",()=>updateStaticPanels());initComms();render(game.activeMenu||"command",false);tickTimer=setInterval(()=>tick(1),5000);setInterval(()=>localStorage.setItem("echoGalacticaSave",JSON.stringify(game)),8000);
